import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import NextTopLoader from "nextjs-toploader";
import { GlobalProvider } from "@/contexts/contexts";
import { ToastContainer, Zoom } from "react-toastify";
import Footer from "@/components/Footer";
import { Analytics } from "@vercel/analytics/next"

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="uz">
      <body className={`${inter.className}`}>
        <GlobalProvider>
          <NextTopLoader
            color="#F43D01"
            height={3}
            showSpinner={false}
          />
          <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable={false}
            pauseOnHover
            theme='colored'
            transition={Zoom}
          />
          <NavBar />
          {children}
          <Footer />
        </GlobalProvider>
        <Analytics />
      </body>
    </html>
  );
}
